# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-01-01 03:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='depart1',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='depart2',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='email',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='extnum',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='fax',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='mobile',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='name',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='phone',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='qq',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
