# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-05-26 07:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flat', '0002_auto_20180101_0353'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='staff_num',
            field=models.CharField(max_length=128, null=True),
        )
    ]
