# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-06-02 09:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flat', '0003_auto_20180526_0754'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='job',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
