# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-22 08:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(max_length=16)),
                ('value', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(max_length=32, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addresslist.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('birthday', models.DateField(null=True)),
                ('jp_pron', models.CharField(max_length=64, null=True)),
                ('ch_pron', models.CharField(max_length=64, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='position',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addresslist.Staff'),
        ),
        migrations.AddField(
            model_name='department',
            name='staffs',
            field=models.ManyToManyField(related_name='departments', through='addresslist.Position', to='addresslist.Staff'),
        ),
        migrations.AddField(
            model_name='department',
            name='superior',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='addresslist.Department'),
        ),
        migrations.AddField(
            model_name='contact',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='addresslist.Staff'),
        ),
        migrations.AlterUniqueTogether(
            name='position',
            unique_together=set([('department', 'staff', 'job')]),
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together=set([('name',)]),
        ),
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together=set([('staff', 'mode', 'value')]),
        ),
    ]
